# Generated by Django 4.2.4 on 2023-10-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время рассылки')),
                ('frequency', models.CharField(choices=[('раз в день', 'Раз в день'), ('раз в неделю', 'Раз в неделю'), ('раз в месяц', 'Раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('завершена', 'Завершена'), ('создана', 'Создана'), ('запущена', 'Запущена')], max_length=150, verbose_name='статус рассылки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='dispatch.client', verbose_name='рассылки клиента')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='тема письма')),
                ('message', models.CharField(max_length=150, verbose_name='текст письма')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dispatch.dispatch', verbose_name='сообщения рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dispatch.dispatch', verbose_name='логи рассылки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
